---
# Bootstrap by installing modules/roles we'll need in other playbooks.
- hosts: all
  become_user: root
  become: true
  tasks:
  - name: install core python libraries
    raw: dnf install -y python2 python2-dnf libselinux-python
    when: ansible_os_family == "RedHat"

# If we go back to using ansible_local for later playbooks, we'll need this again.
# - name: install core python libraries
#   raw: ansible-galaxy install gantsign.golang
